-- ═══════════════════════════════════════════════════════════════════════════
-- TAKI — فحص اكتمال جدة: هل كل ما يناديه التطبيق موجود على الخادم؟
--
-- يقرأ فقط. لا يكتب ولا يغيّر شيئاً إطلاقاً.
--
-- القوائم مستخرجة آلياً من كود التطبيق (`.rpc('…')` و`.from('…')`) في
-- الإصدار v13.83: 136 دالة و28 جدولاً/عرضاً.
-- أي سطر يظهر في القسمين ١ أو ٢ = خاصيّة مكسورة عند المستخدم.
-- ═══════════════════════════════════════════════════════════════════════════

\echo '════ ١ · دوال يناديها التطبيق وغير موجودة على هذا الخادم ════'
WITH called(name) AS (VALUES
        ('account_exists'),
        ('admin_activity_heatmap'),
        ('admin_ai_analyst'),
        ('admin_ai_custom'),
        ('admin_ai_funnel'),
        ('admin_ai_hours'),
        ('admin_ai_matrix'),
        ('admin_ai_pulse2'),
        ('admin_ai_seller_competitors'),
        ('admin_ai_seller_report'),
        ('admin_apply_subscription'),
        ('admin_authenticity_stats'),
        ('admin_booking_funnel'),
        ('admin_bot_analytics'),
        ('admin_broadcast_notification'),
        ('admin_browse_no_book'),
        ('admin_category_funnel'),
        ('admin_churned_subscribers'),
        ('admin_custom_draw'),
        ('admin_custom_draw_preview'),
        ('admin_daily_metrics'),
        ('admin_delete_flag'),
        ('admin_delete_location'),
        ('admin_delete_message'),
        ('admin_delete_warning'),
        ('admin_demote_user'),
        ('admin_first_members'),
        ('admin_geo_insights'),
        ('admin_geographic_breakdown'),
        ('admin_get_thread_messages'),
        ('admin_gmv_monthly'),
        ('admin_health_check'),
        ('admin_investor_kpis'),
        ('admin_list_complaints'),
        ('admin_list_gateways'),
        ('admin_list_message_threads'),
        ('admin_list_payment_attempts'),
        ('admin_list_platform_settings'),
        ('admin_list_reports'),
        ('admin_list_sponsors'),
        ('admin_list_staff'),
        ('admin_list_warned_users'),
        ('admin_lookup_by_date'),
        ('admin_lookup_by_month'),
        ('admin_lookup_by_year'),
        ('admin_moderation_flags'),
        ('admin_moderation_overview'),
        ('admin_mrr_monthly'),
        ('admin_notify_user'),
        ('admin_payment_gateway_status'),
        ('admin_payment_log'),
        ('admin_payment_log_export'),
        ('admin_payment_log_stats'),
        ('admin_promote_user'),
        ('admin_range_summary'),
        ('admin_referral_stats'),
        ('admin_remove_sponsor'),
        ('admin_reset_contest_winners'),
        ('admin_retention_curve'),
        ('admin_revenue_forecast'),
        ('admin_search_users'),
        ('admin_set_booking_ban'),
        ('admin_set_complaint_status'),
        ('admin_set_flag_status'),
        ('admin_set_gateway_blocked'),
        ('admin_set_permissions'),
        ('admin_set_report_status'),
        ('admin_set_sponsor'),
        ('admin_soft_delete_user'),
        ('admin_subscription_growth'),
        ('admin_subscription_lifecycle'),
        ('admin_subscription_timeline'),
        ('admin_suspended_accounts'),
        ('admin_sync_package_limits'),
        ('admin_test_message_event'),
        ('admin_top_activity'),
        ('admin_top_buyers'),
        ('admin_top_sellers'),
        ('admin_update_user'),
        ('admin_upsert_location'),
        ('admin_user_cohorts'),
        ('admin_user_warnings'),
        ('admin_vat_status_summary'),
        ('admin_warn_user'),
        ('authenticity_counts'),
        ('bot_create_link_token'),
        ('bot_login_by_phone'),
        ('broadcast_campaign'),
        ('browse_bookings'),
        ('browse_deals'),
        ('browse_nearby'),
        ('cancel_unverified_signup'),
        ('cast_authenticity_vote'),
        ('contest_counts'),
        ('contest_public_results'),
        ('deal_payment_mode'),
        ('delete_rating'),
        ('delete_user_account'),
        ('draw_contest_winners'),
        ('find_email_by_phone'),
        ('get_booking_card'),
        ('get_bookings_timeline'),
        ('get_live_stats'),
        ('get_my_account_status'),
        ('get_my_gateway'),
        ('get_my_referral_code'),
        ('get_recent_activity'),
        ('increment_deal_click'),
        ('increment_deal_view'),
        ('invoice_customer_details'),
        ('log_activity'),
        ('log_moderation_flag'),
        ('mark_booking_messages_read'),
        ('merchant_accept_gateway_agreement'),
        ('merchant_set_gateway'),
        ('merchant_set_payment_modes'),
        ('merchant_set_subscription_renew'),
        ('merchant_toggle_gateway'),
        ('my_contest_entry'),
        ('my_referral_stats'),
        ('record_analytics_events'),
        ('record_subscription_payment'),
        ('record_user_consent'),
        ('restore_my_account'),
        ('seller_order_stats'),
        ('send_booking_message'),
        ('session_heartbeat'),
        ('set_rating_reply'),
        ('soft_delete_my_account'),
        ('store_follower_count'),
        ('submit_contest_entry'),
        ('toggle_rating_like'),
        ('track_app_open'),
        ('track_search'),
        ('track_store_view'),
        ('update_rating')
)
SELECT c.name AS "❌ دالة مفقودة"
  FROM called c
 WHERE NOT EXISTS (
        SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'public' AND p.proname = c.name)
 ORDER BY 1;

\echo '════ ٢ · جداول/عروض يقرأ منها التطبيق وغير موجودة ════'
WITH used(name) AS (VALUES
        ('admin_draws'),
        ('admin_impersonation_log'),
        ('banners'),
        ('booking_messages'),
        ('bookings'),
        ('complaints'),
        ('contest_entries'),
        ('contests'),
        ('deals'),
        ('email_outbox'),
        ('expense_invoices'),
        ('favorites'),
        ('locations'),
        ('merchant_subscriptions'),
        ('moderation_terms'),
        ('notifications'),
        ('platform_settings'),
        ('promo_impressions'),
        ('promotional_campaigns'),
        ('push_subscriptions'),
        ('ratings'),
        ('reports'),
        ('sellers_public'),
        ('sponsors'),
        ('store_branches'),
        ('store_profiles'),
        ('subscription_payments'),
        ('users')
)
SELECT u.name AS "❌ جدول مفقود"
  FROM used u
 WHERE NOT EXISTS (
        SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = 'public' AND c.relname = u.name
           AND c.relkind IN ('r','v','m','p','f'))
 ORDER BY 1;

\echo '════ ٣ · الحصيلة ════'
WITH called(name) AS (VALUES
        ('account_exists'),
        ('admin_activity_heatmap'),
        ('admin_ai_analyst'),
        ('admin_ai_custom'),
        ('admin_ai_funnel'),
        ('admin_ai_hours'),
        ('admin_ai_matrix'),
        ('admin_ai_pulse2'),
        ('admin_ai_seller_competitors'),
        ('admin_ai_seller_report'),
        ('admin_apply_subscription'),
        ('admin_authenticity_stats'),
        ('admin_booking_funnel'),
        ('admin_bot_analytics'),
        ('admin_broadcast_notification'),
        ('admin_browse_no_book'),
        ('admin_category_funnel'),
        ('admin_churned_subscribers'),
        ('admin_custom_draw'),
        ('admin_custom_draw_preview'),
        ('admin_daily_metrics'),
        ('admin_delete_flag'),
        ('admin_delete_location'),
        ('admin_delete_message'),
        ('admin_delete_warning'),
        ('admin_demote_user'),
        ('admin_first_members'),
        ('admin_geo_insights'),
        ('admin_geographic_breakdown'),
        ('admin_get_thread_messages'),
        ('admin_gmv_monthly'),
        ('admin_health_check'),
        ('admin_investor_kpis'),
        ('admin_list_complaints'),
        ('admin_list_gateways'),
        ('admin_list_message_threads'),
        ('admin_list_payment_attempts'),
        ('admin_list_platform_settings'),
        ('admin_list_reports'),
        ('admin_list_sponsors'),
        ('admin_list_staff'),
        ('admin_list_warned_users'),
        ('admin_lookup_by_date'),
        ('admin_lookup_by_month'),
        ('admin_lookup_by_year'),
        ('admin_moderation_flags'),
        ('admin_moderation_overview'),
        ('admin_mrr_monthly'),
        ('admin_notify_user'),
        ('admin_payment_gateway_status'),
        ('admin_payment_log'),
        ('admin_payment_log_export'),
        ('admin_payment_log_stats'),
        ('admin_promote_user'),
        ('admin_range_summary'),
        ('admin_referral_stats'),
        ('admin_remove_sponsor'),
        ('admin_reset_contest_winners'),
        ('admin_retention_curve'),
        ('admin_revenue_forecast'),
        ('admin_search_users'),
        ('admin_set_booking_ban'),
        ('admin_set_complaint_status'),
        ('admin_set_flag_status'),
        ('admin_set_gateway_blocked'),
        ('admin_set_permissions'),
        ('admin_set_report_status'),
        ('admin_set_sponsor'),
        ('admin_soft_delete_user'),
        ('admin_subscription_growth'),
        ('admin_subscription_lifecycle'),
        ('admin_subscription_timeline'),
        ('admin_suspended_accounts'),
        ('admin_sync_package_limits'),
        ('admin_test_message_event'),
        ('admin_top_activity'),
        ('admin_top_buyers'),
        ('admin_top_sellers'),
        ('admin_update_user'),
        ('admin_upsert_location'),
        ('admin_user_cohorts'),
        ('admin_user_warnings'),
        ('admin_vat_status_summary'),
        ('admin_warn_user'),
        ('authenticity_counts'),
        ('bot_create_link_token'),
        ('bot_login_by_phone'),
        ('broadcast_campaign'),
        ('browse_bookings'),
        ('browse_deals'),
        ('browse_nearby'),
        ('cancel_unverified_signup'),
        ('cast_authenticity_vote'),
        ('contest_counts'),
        ('contest_public_results'),
        ('deal_payment_mode'),
        ('delete_rating'),
        ('delete_user_account'),
        ('draw_contest_winners'),
        ('find_email_by_phone'),
        ('get_booking_card'),
        ('get_bookings_timeline'),
        ('get_live_stats'),
        ('get_my_account_status'),
        ('get_my_gateway'),
        ('get_my_referral_code'),
        ('get_recent_activity'),
        ('increment_deal_click'),
        ('increment_deal_view'),
        ('invoice_customer_details'),
        ('log_activity'),
        ('log_moderation_flag'),
        ('mark_booking_messages_read'),
        ('merchant_accept_gateway_agreement'),
        ('merchant_set_gateway'),
        ('merchant_set_payment_modes'),
        ('merchant_set_subscription_renew'),
        ('merchant_toggle_gateway'),
        ('my_contest_entry'),
        ('my_referral_stats'),
        ('record_analytics_events'),
        ('record_subscription_payment'),
        ('record_user_consent'),
        ('restore_my_account'),
        ('seller_order_stats'),
        ('send_booking_message'),
        ('session_heartbeat'),
        ('set_rating_reply'),
        ('soft_delete_my_account'),
        ('store_follower_count'),
        ('submit_contest_entry'),
        ('toggle_rating_like'),
        ('track_app_open'),
        ('track_search'),
        ('track_store_view'),
        ('update_rating')
), used(name) AS (VALUES
        ('admin_draws'),
        ('admin_impersonation_log'),
        ('banners'),
        ('booking_messages'),
        ('bookings'),
        ('complaints'),
        ('contest_entries'),
        ('contests'),
        ('deals'),
        ('email_outbox'),
        ('expense_invoices'),
        ('favorites'),
        ('locations'),
        ('merchant_subscriptions'),
        ('moderation_terms'),
        ('notifications'),
        ('platform_settings'),
        ('promo_impressions'),
        ('promotional_campaigns'),
        ('push_subscriptions'),
        ('ratings'),
        ('reports'),
        ('sellers_public'),
        ('sponsors'),
        ('store_branches'),
        ('store_profiles'),
        ('subscription_payments'),
        ('users')
)
SELECT
  (SELECT count(*) FROM called)                                            AS "دوال يناديها التطبيق",
  (SELECT count(*) FROM called c WHERE EXISTS (SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname=c.name))                      AS "منها موجودة ✅",
  (SELECT count(*) FROM used)                                              AS "جداول يستعملها",
  (SELECT count(*) FROM used u WHERE EXISTS (SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname='public' AND c.relname=u.name
        AND c.relkind IN ('r','v','m','p','f')))                           AS "منها موجودة ✅",
  (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public')                                              AS "إجمالي دوال الخادم";

\echo '════ ٤ · عدّ صفوف الجداول الأساسية (تحقّق من البيانات) ════'
SELECT 'users' AS "الجدول", count(*) AS "الصفوف" FROM public.users
UNION ALL SELECT 'deals',            count(*) FROM public.deals
UNION ALL SELECT 'bookings',         count(*) FROM public.bookings
UNION ALL SELECT 'booking_messages', count(*) FROM public.booking_messages
UNION ALL SELECT 'notifications',    count(*) FROM public.notifications
UNION ALL SELECT 'store_profiles',   count(*) FROM public.store_profiles
UNION ALL SELECT 'store_branches',   count(*) FROM public.store_branches
UNION ALL SELECT 'ratings',          count(*) FROM public.ratings
UNION ALL SELECT 'favorites',        count(*) FROM public.favorites
UNION ALL SELECT 'صور في المستودع',  count(*) FROM storage.objects WHERE bucket_id='deals';
